/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MovieDetails = IDL.Record({
  'title' : IDL.Text,
  'synopsis' : IDL.Text,
  'genre' : IDL.Text,
  'castList' : IDL.Vec(IDL.Text),
  'releaseDate' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMovieDetails' : IDL.Func([], [IDL.Vec(MovieDetails)], ['query']),
  'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getMovieDetails' : IDL.Func([IDL.Text], [MovieDetails], ['query']),
  'getNewsletterEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'setMovieDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'subscribe' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MovieDetails = IDL.Record({
    'title' : IDL.Text,
    'synopsis' : IDL.Text,
    'genre' : IDL.Text,
    'castList' : IDL.Vec(IDL.Text),
    'releaseDate' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMovieDetails' : IDL.Func([], [IDL.Vec(MovieDetails)], ['query']),
    'getContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getMovieDetails' : IDL.Func([IDL.Text], [MovieDetails], ['query']),
    'getNewsletterEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setMovieDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'subscribe' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };