/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface MovieDetails {
  'title' : string,
  'synopsis' : string,
  'genre' : string,
  'castList' : Array<string>,
  'releaseDate' : string,
}
export interface _SERVICE {
  'getAllMovieDetails' : ActorMethod<[], Array<MovieDetails>>,
  'getContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getMovieDetails' : ActorMethod<[string], MovieDetails>,
  'getNewsletterEmails' : ActorMethod<[], Array<string>>,
  'setMovieDetails' : ActorMethod<
    [string, string, string, string, string, Array<string>],
    undefined
  >,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'subscribe' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];